# Generated by Django 5.2.7 on 2025-10-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artistes/')),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('annee_creation', models.CharField(blank=True, max_length=20)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='oeuvres/')),
                ('fichier_3d', models.FileField(blank=True, null=True, upload_to='oeuvres/3d/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='galerie.artiste')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galerie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('3d', '3D')], max_length=50)),
                ('fichier', models.FileField(upload_to='medias/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='galerie.oeuvre')),
            ],
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('image_affiche', models.ImageField(blank=True, null=True, upload_to='expositions/')),
                ('oeuvres', models.ManyToManyField(related_name='expositions', to='galerie.oeuvre')),
            ],
        ),
    ]
