# Generated by Django 5.2.7 on 2025-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/artistes/'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='image_affiche',
            field=models.ImageField(blank=True, null=True, upload_to='media/expositions/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='fichier_3d',
            field=models.FileField(blank=True, null=True, upload_to='media/oeuvres/3d/'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='media/oeuvres/'),
        ),
    ]
