# Generated by Django 5.2.7 on 2025-10-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_alter_artiste_photo_alter_exposition_image_affiche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artistes/'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='image_affiche',
            field=models.ImageField(blank=True, null=True, upload_to='expositions/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=models.FileField(upload_to='fich'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='fichier_3d',
            field=models.FileField(blank=True, null=True, upload_to='oeuvres/3d/'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='oeuvres/'),
        ),
    ]
